// src/lib/civilLawData.js
// Federal and Provincial statutes relevant to Canadian criminal law scenarios.
// Sources: justice.gc.ca, laws-lois.justice.gc.ca, ontario.ca/laws, bclaws.gov.bc.ca, alberta.ca/alberta-king-s-printer
// Used by api/verify.js to validate AI-suggested civil_law citations.

// ── Base URLs ─────────────────────────────────────────────────────────────────
const CDSA_BASE    = "https://laws-lois.justice.gc.ca/eng/acts/c-38.8";
const YCJA_BASE    = "https://laws-lois.justice.gc.ca/eng/acts/y-1.5";
const CHRA_BASE    = "https://laws-lois.justice.gc.ca/eng/acts/h-6";
const CC_BASE      = "https://laws-lois.justice.gc.ca/eng/acts/c-46";
const CCRA_BASE    = "https://laws-lois.justice.gc.ca/eng/acts/c-44.6";
const EVIDENCE_BASE = "https://laws-lois.justice.gc.ca/eng/acts/c-5";
const ON_HTA_BASE   = "https://www.ontario.ca/laws/statute/90h08";
const ON_RTA_BASE   = "https://www.ontario.ca/laws/statute/06r17";
const ON_HRC_BASE   = "https://www.ontario.ca/laws/statute/90h19";
const BC_MVA_BASE   = "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96318_00";
const BC_RTA_BASE   = "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02078_01";
const BC_HRC_BASE   = "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96210_01";
const AB_TSA_BASE   = "https://www.alberta.ca/traffic-safety-act";
const AB_RTA_BASE   = "https://www.alberta.ca/residential-tenancies-act";
const AB_HRA_BASE   = "https://www.alberta.ca/alberta-human-rights-act";

// ── Federal: CDSA ─────────────────────────────────────────────────────────────
const CDSA_SECTIONS = new Map([
  ["2", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Definitions",
    summary: "Definitions for the purposes of this Act, including 'substance', 'traffic', 'produce', and the Schedule classifications.",
    relevance: "drug charges, substance classification, Schedule I-V, trafficking definition",
    url: `${CDSA_BASE}/section-2.html`,
  }],
  ["4", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Possession of substance",
    summary: "Except as authorized under the regulations, no person shall possess a substance included in Schedule I, II or III.",
    relevance: "drug possession, constructive possession, knowledge, Schedule I-III substances, cannabis, cocaine, heroin, fentanyl",
    url: `${CDSA_BASE}/section-4.html`,
  }],
  ["5", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Trafficking in substance",
    summary: "No person shall traffic in a substance included in Schedule I, II, III, IV or V or in any substance represented or held out by that person to be such a substance.",
    relevance: "drug trafficking, selling drugs, distributing controlled substances, Schedule I penalties",
    url: `${CDSA_BASE}/section-5.html`,
  }],
  ["6", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Importing and exporting",
    summary: "Except as authorized under the regulations, no person shall import into Canada or export from Canada a substance included in Schedule I, II, III, IV, V or VI.",
    relevance: "drug importation, drug exportation, border smuggling, Schedule I-VI",
    url: `${CDSA_BASE}/section-6.html`,
  }],
  ["7", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Production of substance",
    summary: "Except as authorized under the regulations, no person shall produce a substance included in Schedule I, II, III, IV or V.",
    relevance: "drug production, grow op, manufacturing narcotics, lab, methamphetamine production",
    url: `${CDSA_BASE}/section-7.html`,
  }],
  ["10", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Purpose of sentencing",
    summary: "Without restricting the generality of the Criminal Code, the fundamental purpose of any sentence for an offence under this Part is to contribute to the respect for the law and the maintenance of a just, peaceful and safe society while encouraging rehabilitation, and treatment in appropriate circumstances, of offenders and acknowledging the harm done to victims and to the community.",
    relevance: "CDSA sentencing principles, aggravating factors, rehabilitation, drug treatment court",
    url: `${CDSA_BASE}/section-10.html`,
  }],

  ["1", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Short Title",
    summary: "Statutory provision dealing with short title.",
    relevance: "federal drug statute, short title",
    url: `${CDSA_BASE}/section-1.html`,
  }],
  ["10.1", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Principles",
    summary: "Statutory provision dealing with principles.",
    relevance: "drug diversion, treatment, alternatives to prosecution",
    url: `${CDSA_BASE}/section-10.1.html`,
  }],
  ["10.2", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Warnings and Referrals",
    summary: "Statutory provision dealing with warnings and referrals.",
    relevance: "drug diversion, police warnings, referral programs",
    url: `${CDSA_BASE}/section-10.2.html`,
  }],
  ["10.7", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Exception for Service Providers",
    summary: "Statutory provision dealing with exception for service providers.",
    relevance: "health service providers, harm reduction, diversion exceptions",
    url: `${CDSA_BASE}/section-10.7.html`,
  }],
  ["11", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Enforcement",
    summary: "Statutory provision dealing with enforcement.",
    relevance: "drug investigations, search and seizure, enforcement powers",
    url: `${CDSA_BASE}/section-11.html`,
  }],
  ["13", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Disposition",
    summary: "Statutory provision dealing with disposition.",
    relevance: "seizure, forfeiture, offence-related property",
    url: `${CDSA_BASE}/section-13.html`,
  }],
  ["14", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Restraint Orders",
    summary: "Statutory provision dealing with restraint orders.",
    relevance: "restraint orders, property seizure, proceeds-related property",
    url: `${CDSA_BASE}/section-14.html`,
  }],
  ["15.1", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Management Orders",
    summary: "Statutory provision dealing with management orders.",
    relevance: "property management, seizure, forfeiture process",
    url: `${CDSA_BASE}/section-15.1.html`,
  }],
  ["16", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Forfeiture",
    summary: "Statutory provision dealing with forfeiture.",
    relevance: "forfeiture, seizure, drug proceeds",
    url: `${CDSA_BASE}/section-16.html`,
  }],
  ["23", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Controlled Substances, Precursors and Chemical Offence-related Property",
    summary: "Statutory provision dealing with controlled substances, precursors and chemical offence-related property.",
    relevance: "controlled substances, precursors, chemical property, forfeiture",
    url: `${CDSA_BASE}/section-23.html`,
  }],
  ["30", {
    jurisdiction: "Federal",
    statute: "Controlled Drugs and Substances Act",
    shortName: "CDSA",
    title: "Inspectors",
    summary: "Statutory provision dealing with inspectors.",
    relevance: "inspection powers, compliance, regulatory enforcement",
    url: `${CDSA_BASE}/section-30.html`,
  }],

]);

// ── Federal: YCJA ─────────────────────────────────────────────────────────────
const YCJA_SECTIONS = new Map([
  ["2", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Definitions — young person",
    summary: "Definitions including 'young person' (a person aged 12 or over and under 18 years at the time of the alleged offence), 'youth justice court', 'adult sentence', and 'youth sentence'.",
    relevance: "youth criminal liability, age of criminal responsibility, 12-17 years old, young person definition",
    url: `${YCJA_BASE}/section-2.html`,
  }],
  ["3", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Declaration of principle",
    summary: "The principles of the youth criminal justice system, including protecting the public, holding young persons accountable proportionately, and promoting rehabilitation and reintegration.",
    relevance: "youth sentencing principles, rehabilitation, accountability, proportionality, Indigenous youth",
    url: `${YCJA_BASE}/section-3.html`,
  }],
  ["38", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Purpose of sentencing",
    summary: "The purpose of the youth sentencing provisions is to hold a young person accountable for an offence through the imposition of just sanctions that have meaningful consequences.",
    relevance: "youth sentence purpose, rehabilitation, reintegration, just sanctions, meaningful consequences",
    url: `${YCJA_BASE}/section-38.html`,
  }],
  ["39", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Committal to custody",
    summary: "A youth justice court shall not commit a young person to custody under section 42 unless specific criteria are met, such as committing a violent offence or failing to comply with non-custodial sentences.",
    relevance: "youth custody, youth incarceration, last resort principle, youth violent offence",
    url: `${YCJA_BASE}/section-39.html`,
  }],
  ["40", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Pre-sentence report",
    summary: "A youth justice court shall, before imposing a youth sentence, consider a pre-sentence report.",
    relevance: "youth pre-sentence report, youth worker, mitigating factors, youth background",
    url: `${YCJA_BASE}/section-40.html`,
  }],
  ["110", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Identity of offender not to be published",
    summary: "Subject to this section, no person shall publish the name of a young person, or any other information related to a young person, if it would identify them as being dealt with under this Act.",
    relevance: "youth publication ban, identity protection, media reporting, young offender privacy",
    url: `${YCJA_BASE}/section-110.html`,
  }],

  ["1", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Short Title",
    summary: "Statutory provision dealing with short title.",
    relevance: "youth justice statute, short title",
    url: `${YCJA_BASE}/section-1.html`,
  }],
  ["4", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Principles and Objectives",
    summary: "Statutory provision dealing with principles and objectives.",
    relevance: "extrajudicial measures, youth justice objectives",
    url: `${YCJA_BASE}/section-4.html`,
  }],
  ["6", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Warnings, Cautions and Referrals",
    summary: "Statutory provision dealing with warnings, cautions and referrals.",
    relevance: "diversion, warnings, cautions, referrals, alternatives to charges",
    url: `${YCJA_BASE}/section-6.html`,
  }],
  ["10", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Extrajudicial Sanctions",
    summary: "Statutory provision dealing with extrajudicial sanctions.",
    relevance: "youth diversion, restorative justice, community sanctions",
    url: `${YCJA_BASE}/section-10.html`,
  }],
  ["13", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Youth Justice Court",
    summary: "Statutory provision dealing with youth justice court.",
    relevance: "youth court, jurisdiction, youth proceedings",
    url: `${YCJA_BASE}/section-13.html`,
  }],
  ["23", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Consent to Prosecute",
    summary: "Statutory provision dealing with consent to prosecute.",
    relevance: "youth prosecution, attorney general consent, charges review",
    url: `${YCJA_BASE}/section-23.html`,
  }],
  ["25", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Right to Counsel",
    summary: "Statutory provision dealing with right to counsel.",
    relevance: "youth right to counsel, arrest, detention, legal aid",
    url: `${YCJA_BASE}/section-25.html`,
  }],
  ["26", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Notices to Parents",
    summary: "Statutory provision dealing with notices to parents.",
    relevance: "youth notice, parent notification, arrest, summons",
    url: `${YCJA_BASE}/section-26.html`,
  }],
  ["28", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Detention and Release",
    summary: "Statutory provision dealing with detention and release.",
    relevance: "youth bail, detention, release conditions",
    url: `${YCJA_BASE}/section-28.html`,
  }],
  ["29", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Release order with conditions",
    summary: "Statutory provision dealing with release order with conditions.",
    relevance: "youth bail conditions, detention justification, public safety",
    url: `${YCJA_BASE}/section-29.html`,
  }],
  ["32", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Appearance",
    summary: "Statutory provision dealing with appearance.",
    relevance: "youth appearance, summons, attendance",
    url: `${YCJA_BASE}/section-32.html`,
  }],
  ["33", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Application for Release from or Detention in Custody",
    summary: "Statutory provision dealing with application for release from or detention in custody.",
    relevance: "youth detention review, bail hearing, release application",
    url: `${YCJA_BASE}/section-33.html`,
  }],
  ["34", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Medical and Psychological Reports",
    summary: "Statutory provision dealing with medical and psychological reports.",
    relevance: "youth reports, mental health, sentencing information",
    url: `${YCJA_BASE}/section-34.html`,
  }],
  ["35", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Referral to Child Welfare Agency",
    summary: "Statutory provision dealing with referral to child welfare agency.",
    relevance: "child welfare, youth supports, intervention",
    url: `${YCJA_BASE}/section-35.html`,
  }],
  ["38", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Purpose and Principles",
    summary: "Statutory provision dealing with purpose and principles.",
    relevance: "youth sentencing, rehabilitation, proportionality, custody as last resort",
    url: `${YCJA_BASE}/section-38.html`,
  }],
  ["41", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Youth Sentences",
    summary: "Statutory provision dealing with youth sentences.",
    relevance: "youth sentence, community supervision, custody",
    url: `${YCJA_BASE}/section-41.html`,
  }],
  ["61", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Adult Sentence and Election",
    summary: "Statutory provision dealing with adult sentence and election.",
    relevance: "adult sentence, youth election, serious offences",
    url: `${YCJA_BASE}/section-61.html`,
  }],
  ["110", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Identity of offender not to be published",
    summary: "Statutory provision dealing with identity of offender not to be published.",
    relevance: "youth publication ban, identity protection, media reporting, young offender privacy",
    url: `${YCJA_BASE}/section-110.html`,
  }],
  ["113", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Fingerprints and Photographs",
    summary: "Statutory provision dealing with fingerprints and photographs.",
    relevance: "youth privacy, fingerprints, publication ban",
    url: `${YCJA_BASE}/section-113.html`,
  }],
  ["117", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Access to Records",
    summary: "Statutory provision dealing with access to records.",
    relevance: "youth records access, confidentiality, disclosure",
    url: `${YCJA_BASE}/section-117.html`,
  }],
  ["125", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Disclosure of Information in a Record",
    summary: "Statutory provision dealing with disclosure of information in a record.",
    relevance: "record disclosure, privacy, youth confidentiality",
    url: `${YCJA_BASE}/section-125.html`,
  }],
  ["128", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Disposition or Destruction of Records and Prohibition on Use and Disclosure",
    summary: "Statutory provision dealing with disposition or destruction of records and prohibition on use and disclosure.",
    relevance: "record destruction, privacy, sealing youth records",
    url: `${YCJA_BASE}/section-128.html`,
  }],
  ["136", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Offences and Punishment",
    summary: "Statutory provision dealing with offences and punishment.",
    relevance: "youth act offences, compliance, penalties",
    url: `${YCJA_BASE}/section-136.html`,
  }],
  ["140", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Application of Criminal Code",
    summary: "Statutory provision dealing with application of criminal code.",
    relevance: "youth procedure, criminal code application, ancillary powers",
    url: `${YCJA_BASE}/section-140.html`,
  }],
  ["146", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Evidence",
    summary: "Statutory provision dealing with evidence.",
    relevance: "youth evidence, admissibility, procedure",
    url: `${YCJA_BASE}/section-146.html`,
  }],
  ["154", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Forms, Regulations and Rules of Court",
    summary: "Statutory provision dealing with forms, regulations and rules of court.",
    relevance: "court forms, rules, youth procedure",
    url: `${YCJA_BASE}/section-154.html`,
  }],
  ["156", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Agreements with Provinces",
    summary: "Statutory provision dealing with agreements with provinces.",
    relevance: "provincial administration, youth justice systems",
    url: `${YCJA_BASE}/section-156.html`,
  }],
  ["157", {
    jurisdiction: "Federal",
    statute: "Youth Criminal Justice Act",
    shortName: "YCJA",
    title: "Programs",
    summary: "Statutory provision dealing with programs.",
    relevance: "youth programming, community supports, diversion",
    url: `${YCJA_BASE}/section-157.html`,
  }],

]);

// ── Federal: CHRA ─────────────────────────────────────────────────────────────
const CHRA_SECTIONS = new Map([
  ["2", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Purpose",
    summary: "The purpose of this Act is to give effect to the principle that all individuals should have an equal opportunity to make for themselves the lives that they are able and wish to have.",
    relevance: "human rights purpose, equal opportunity, accommodation, federal jurisdiction",
    url: `${CHRA_BASE}/section-2.html`,
  }],
  ["3", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Prohibited grounds of discrimination",
    summary: "The prohibited grounds of discrimination are race, national or ethnic origin, colour, religion, age, sex, sexual orientation, gender identity or expression, marital status, family status, genetic characteristics, disability and conviction for an offence for which a pardon has been granted.",
    relevance: "discrimination grounds, race, sex, religion, disability, sexual orientation, gender identity, hate crimes",
    url: `${CHRA_BASE}/section-3.html`,
  }],

  ["5", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Discriminatory Practices",
    summary: "Statutory provision dealing with discriminatory practices.",
    relevance: "human rights discrimination, federal services, employment, accommodation",
    url: `${CHRA_BASE}/section-5.html`,
  }],
  ["6", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Denial of commercial premises or residential accommodation",
    summary: "Statutory provision dealing with denial of commercial premises or residential accommodation.",
    relevance: "housing discrimination, commercial premises, tenancy, accommodation",
    url: `${CHRA_BASE}/section-6.html`,
  }],
  ["7", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Employment",
    summary: "Statutory provision dealing with employment.",
    relevance: "employment discrimination, hiring, termination, promotion",
    url: `${CHRA_BASE}/section-7.html`,
  }],
  ["10", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Discriminatory policy or practice",
    summary: "Statutory provision dealing with discriminatory policy or practice.",
    relevance: "employment policy, systemic discrimination, job opportunities",
    url: `${CHRA_BASE}/section-10.html`,
  }],
  ["14", {
    jurisdiction: "Federal",
    statute: "Canadian Human Rights Act",
    shortName: "CHRA",
    title: "Harassment",
    summary: "Statutory provision dealing with harassment.",
    relevance: "harassment, sexual harassment, workplace harassment, public services",
    url: `${CHRA_BASE}/section-14.html`,
  }],

]);

// ── Federal: Criminal Code (Sentencing) ──────────────────────────────────────
const CC_SENTENCING = new Map([
  ["718", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Purpose of sentencing",
    summary: "The fundamental purpose of sentencing is to protect society and to contribute to respect for the law and the maintenance of a just, peaceful and safe society.",
    relevance: "sentencing purpose, denunciation, deterrence, rehabilitation, reparation, sentencing principles",
    url: `${CC_BASE}/section-718.html`,
  }],
  ["718.1", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Fundamental principle of sentencing",
    summary: "A sentence must be proportionate to the gravity of the offence and the degree of responsibility of the offender.",
    relevance: "proportionality in sentencing, gravity of offence, moral blameworthiness",
    url: `${CC_BASE}/section-718.1.html`,
  }],
  ["718.2", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Other sentencing principles",
    summary: "Aggravating and mitigating circumstances, parity, totality, restraint, and specific attention to Aboriginal offenders (Gladue principles).",
    relevance: "aggravating factors, mitigating factors, hate crime sentencing, Gladue principles, Aboriginal offenders",
    url: `${CC_BASE}/section-718.2.html`,
  }],
  ["719", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Commencement of sentence",
    summary: "A sentence commences when it is imposed, except where a relevant enactment otherwise provides.",
    relevance: "sentence start date, pre-sentence custody credit, remand credit, 1.5x credit",
    url: `${CC_BASE}/section-719.html`,
  }],
  ["722", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Victim impact statement",
    summary: "When determining the sentence, the court shall consider any statement of a victim describing the physical or emotional harm result of the offence.",
    relevance: "victim impact statement, victim's rights, harm, loss, sentencing",
    url: `${CC_BASE}/section-722.html`,
  }],
  ["730", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Absolute and conditional discharges",
    summary: "Where an accused pleads guilty to or is found guilty of an offence, the court may direct that the accused be discharged absolutely or conditionally.",
    relevance: "discharge, conditional discharge, absolute discharge, no conviction, first offence",
    url: `${CC_BASE}/section-730.html`,
  }],
  ["731", {
    jurisdiction: "Federal",
    statute: "Criminal Code",
    shortName: "CC",
    title: "Probation",
    summary: "Where a person is convicted of an offence, a court may suspend the passing of sentence and direct that the offender be released on probation.",
    relevance: "probation order, suspended sentence, community supervision, conditions",
    url: `${CC_BASE}/section-731.html`,
  }],
]);

// ── Federal: Canada Evidence Act ─────────────────────────────────────────────
const EVIDENCE_SECTIONS = new Map([
  ["16", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Witness whose capacity is in question",
    summary: "Procedures for witnesses whose mental capacity is challenged, including the requirement to understand the nature of an oath.",
    relevance: "competency of witness, mental disability, understanding oath, ability to communicate",
    url: `${EVIDENCE_BASE}/section-16.html`,
  }],
  ["16.1", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Person under fourteen years of age",
    summary: "A person under fourteen years of age is presumed to have the capacity to testify.",
    relevance: "child witness, testimony of minors, promise to tell the truth, child evidence",
    url: `${EVIDENCE_BASE}/section-16.1.html`,
  }],

  ["2", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Application",
    summary: "Statutory provision dealing with application.",
    relevance: "evidence law, federal evidentiary rules",
    url: `${EVIDENCE_BASE}/section-2.html`,
  }],
  ["3", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Witnesses",
    summary: "Statutory provision dealing with witnesses.",
    relevance: "competency, witness evidence, testimony",
    url: `${EVIDENCE_BASE}/section-3.html`,
  }],
  ["13", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Oaths and Solemn Affirmations",
    summary: "Statutory provision dealing with oaths and solemn affirmations.",
    relevance: "oath, affirmation, witness evidence",
    url: `${EVIDENCE_BASE}/section-13.html`,
  }],
  ["17", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Judicial Notice",
    summary: "Statutory provision dealing with judicial notice.",
    relevance: "judicial notice, proof, admissibility",
    url: `${EVIDENCE_BASE}/section-17.html`,
  }],
  ["19", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Documentary Evidence",
    summary: "Statutory provision dealing with documentary evidence.",
    relevance: "documents, records, documentary proof",
    url: `${EVIDENCE_BASE}/section-19.html`,
  }],
  ["36.1", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Interpretation",
    summary: "Statutory provision dealing with interpretation.",
    relevance: "evidence statute interpretation, federal evidence",
    url: `${EVIDENCE_BASE}/section-36.1.html`,
  }],
  ["37", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "Specified Public Interest",
    summary: "Statutory provision dealing with specified public interest.",
    relevance: "confidential information, public interest, disclosure disputes",
    url: `${EVIDENCE_BASE}/section-37.html`,
  }],
  ["38", {
    jurisdiction: "Federal",
    statute: "Canada Evidence Act",
    shortName: "CEA",
    title: "International Relations and National Defence and National Security",
    summary: "Statutory provision dealing with international relations and national defence and national security.",
    relevance: "national security, international relations, sensitive evidence",
    url: `${EVIDENCE_BASE}/section-38.html`,
  }],

]);

// ── Federal: CCRA ─────────────────────────────────────────────────────────────
const CCRA_SECTIONS = new Map([
  ["100", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Purpose of conditional release",
    summary: "Conditional release facilitates rehabilitation and reintegration into the community as law-abiding citizens.",
    relevance: "parole, statutory release, conditional release purpose, rehabilitation, reintegration",
    url: `${CCRA_BASE}/section-100.html`,
  }],
  ["101", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Principles guiding the Board",
    summary: "The principles that shall guide the Board and the provincial parole boards in achieving the purpose of conditional release.",
    relevance: "parole board principles, public protection, parole decision, risk assessment",
    url: `${CCRA_BASE}/section-101.html`,
  }],

  ["2", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Interpretation",
    summary: "Statutory provision dealing with interpretation.",
    relevance: "corrections, parole, statutory interpretation",
    url: `${CCRA_BASE}/section-2.html`,
  }],
  ["3", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Purpose and Principles",
    summary: "Statutory provision dealing with purpose and principles.",
    relevance: "corrections purpose, rehabilitation, reintegration, public safety",
    url: `${CCRA_BASE}/section-3.html`,
  }],
  ["5", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Correctional Service of Canada",
    summary: "Statutory provision dealing with correctional service of canada.",
    relevance: "CSC, correctional service, federal corrections",
    url: `${CCRA_BASE}/section-5.html`,
  }],
  ["11", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Reception of Inmates",
    summary: "Statutory provision dealing with reception of inmates.",
    relevance: "institutional intake, inmate reception, custody",
    url: `${CCRA_BASE}/section-11.html`,
  }],
  ["15.1", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Correctional Plans",
    summary: "Statutory provision dealing with correctional plans.",
    relevance: "correctional plan, reintegration, inmate programming",
    url: `${CCRA_BASE}/section-15.1.html`,
  }],
  ["17", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Escorted Temporary Absences",
    summary: "Statutory provision dealing with escorted temporary absences.",
    relevance: "temporary absence, release planning, custody management",
    url: `${CCRA_BASE}/section-17.html`,
  }],
  ["18", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Work Releases",
    summary: "Statutory provision dealing with work releases.",
    relevance: "work release, temporary release, reintegration",
    url: `${CCRA_BASE}/section-18.html`,
  }],
  ["23", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Information",
    summary: "Statutory provision dealing with information.",
    relevance: "offender information, correctional records, disclosure",
    url: `${CCRA_BASE}/section-23.html`,
  }],
  ["28", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Placement and Transfer of Inmates",
    summary: "Statutory provision dealing with placement and transfer of inmates.",
    relevance: "transfer, classification, institutional placement",
    url: `${CCRA_BASE}/section-28.html`,
  }],
  ["29.1", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Security Classification",
    summary: "Statutory provision dealing with security classification.",
    relevance: "security level, classification, custody placement",
    url: `${CCRA_BASE}/section-29.1.html`,
  }],
  ["102", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Criteria for granting parole",
    summary: "Statutory provision dealing with criteria for granting parole.",
    relevance: "parole eligibility, risk, reintegration, public safety",
    url: `${CCRA_BASE}/section-102.html`,
  }],
  ["103", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Constitution and Jurisdiction of Board",
    summary: "Statutory provision dealing with constitution and jurisdiction of board.",
    relevance: "parole board, jurisdiction, decision-making",
    url: `${CCRA_BASE}/section-103.html`,
  }],
  ["112", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Constitution and Jurisdiction of Provincial Boards",
    summary: "Statutory provision dealing with constitution and jurisdiction of provincial boards.",
    relevance: "provincial parole board, parole jurisdiction",
    url: `${CCRA_BASE}/section-112.html`,
  }],
  ["115", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Unescorted Temporary Absence",
    summary: "Statutory provision dealing with unescorted temporary absence.",
    relevance: "UTA, temporary release, parole planning",
    url: `${CCRA_BASE}/section-115.html`,
  }],
  ["119", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Eligibility for Parole",
    summary: "Statutory provision dealing with eligibility for parole.",
    relevance: "parole eligibility, sentence length, review timing",
    url: `${CCRA_BASE}/section-119.html`,
  }],
  ["122", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Parole Reviews",
    summary: "Statutory provision dealing with parole reviews.",
    relevance: "parole hearing, review, release decision",
    url: `${CCRA_BASE}/section-122.html`,
  }],
  ["127", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Statutory Release",
    summary: "Statutory provision dealing with statutory release.",
    relevance: "statutory release, release date, custody",
    url: `${CCRA_BASE}/section-127.html`,
  }],
  ["128", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Effect of Parole, Statutory Release or Unescorted Temporary Absence",
    summary: "Statutory provision dealing with effect of parole, statutory release or unescorted temporary absence.",
    relevance: "parole effect, statutory release, sentence administration",
    url: `${CCRA_BASE}/section-128.html`,
  }],
  ["133", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Conditions of Release",
    summary: "Statutory provision dealing with conditions of release.",
    relevance: "release conditions, parole conditions, supervision",
    url: `${CCRA_BASE}/section-133.html`,
  }],
  ["134.1", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Conditions for Long-Term Supervision",
    summary: "Statutory provision dealing with conditions for long-term supervision.",
    relevance: "long-term supervision, parole-like conditions, release planning",
    url: `${CCRA_BASE}/section-134.1.html`,
  }],
  ["135", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Suspension, Termination, Revocation and Inoperativeness of Parole, Statutory Release or Long-Term Supervision",
    summary: "Statutory provision dealing with suspension, termination, revocation and inoperativeness of parole, statutory release or long-term supervision.",
    relevance: "revocation, suspension, supervision, parole breach",
    url: `${CCRA_BASE}/section-135.html`,
  }],
  ["140", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Review Hearings",
    summary: "Statutory provision dealing with review hearings.",
    relevance: "review hearing, supervision review, correctional procedure",
    url: `${CCRA_BASE}/section-140.html`,
  }],
  ["141", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Disclosure of Information",
    summary: "Statutory provision dealing with disclosure of information.",
    relevance: "information disclosure, parole file, offender records",
    url: `${CCRA_BASE}/section-141.html`,
  }],
  ["145", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Review and Evidence",
    summary: "Statutory provision dealing with review and evidence.",
    relevance: "parole evidence, review record, procedural fairness",
    url: `${CCRA_BASE}/section-145.html`,
  }],
  ["146", {
    jurisdiction: "Federal",
    statute: "Corrections and Conditional Release Act",
    shortName: "CCRA",
    title: "Organization of the Board",
    summary: "Statutory provision dealing with organization of the board.",
    relevance: "parole board structure, appeal division, organization",
    url: `${CCRA_BASE}/section-146.html`,
  }],

]);

// ── Ontario: Highway Traffic Act ─────────────────────────────────────────────
const ON_HTA_SECTIONS = new Map([
  ["53", {
    jurisdiction: "Ontario",
    statute: "Highway Traffic Act",
    shortName: "HTA",
    title: "Driving while licence suspended",
    summary: "Every person who drives a motor vehicle on a highway while his or her driver’s licence is suspended is guilty of an offence.",
    relevance: "driving while suspended, provincial traffic offences",
    url: `${ON_HTA_BASE}`,
  }],
  ["128", {
    jurisdiction: "Ontario",
    statute: "Highway Traffic Act",
    shortName: "HTA",
    title: "Rate of speed",
    summary: "Statutory limits on speed for various highway types.",
    relevance: "speeding, traffic safety",
    url: `${ON_HTA_BASE}`,
  }],
  ["130", {
    jurisdiction: "Ontario",
    statute: "Highway Traffic Act",
    shortName: "HTA",
    title: "Careless driving",
    summary: "Driving without due care and attention or without reasonable consideration for other persons.",
    relevance: "careless driving, provincial driving offence",
    url: `${ON_HTA_BASE}`,
  }],
]);

// ── Ontario: Residential Tenancies Act ───────────────────────────────────────
const ON_RTA_SECTIONS = new Map([
  ["20", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Landlord's responsibility to repair",
    summary: "A landlord is responsible for providing and maintaining a residential complex and the rental units in a good state of repair.",
    relevance: "tenancy disputes, maintenance, habitability",
    url: `${ON_RTA_BASE}`,
  }],

  ["1", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Interpretation",
    summary: "Statutory provision dealing with interpretation.",
    relevance: "residential tenancies, landlord tenant terms, Ontario tenancy law",
    url: ON_RTA_BASE,
  }],
  ["2", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Application",
    summary: "Statutory provision dealing with application.",
    relevance: "Ontario tenancy coverage, rental units, exclusions",
    url: ON_RTA_BASE,
  }],
  ["3", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Act prevails",
    summary: "Statutory provision dealing with act prevails.",
    relevance: "statutory priority, tenancy agreements, landlord obligations",
    url: ON_RTA_BASE,
  }],
  ["4", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Crown is bound",
    summary: "Statutory provision dealing with crown is bound.",
    relevance: "provincial tenancy obligations, Crown landlord",
    url: ON_RTA_BASE,
  }],
  ["21", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Assignment and sublease",
    summary: "Statutory provision dealing with assignment and sublease.",
    relevance: "assignment, sublet, landlord consent",
    url: ON_RTA_BASE,
  }],
  ["22", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Entry of premises",
    summary: "Statutory provision dealing with entry of premises.",
    relevance: "landlord entry, access, notice",
    url: ON_RTA_BASE,
  }],
  ["23", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Locks and security devices",
    summary: "Statutory provision dealing with locks and security devices.",
    relevance: "tenant security, lock changes, landlord access",
    url: ON_RTA_BASE,
  }],
  ["24", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Landlord's remedies",
    summary: "Statutory provision dealing with landlord's remedies.",
    relevance: "landlord remedies, breach, tenancy enforcement",
    url: ON_RTA_BASE,
  }],
  ["25", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Repudiation of tenancy",
    summary: "Statutory provision dealing with repudiation of tenancy.",
    relevance: "repudiation, abandonment, tenancy end",
    url: ON_RTA_BASE,
  }],
  ["26", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Termination of tenancy for substantial breach",
    summary: "Statutory provision dealing with termination of tenancy for substantial breach.",
    relevance: "breach, termination, landlord notice",
    url: ON_RTA_BASE,
  }],
  ["27", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Termination of tenancy for damage or assault",
    summary: "Statutory provision dealing with termination of tenancy for damage or assault.",
    relevance: "damage, assault, eviction, termination",
    url: ON_RTA_BASE,
  }],
  ["29", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Recovery of damages",
    summary: "Statutory provision dealing with recovery of damages.",
    relevance: "damages, tenancy losses, landlord claims",
    url: ON_RTA_BASE,
  }],
  ["30", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Notice to vacate",
    summary: "Statutory provision dealing with notice to vacate.",
    relevance: "notice to vacate, eviction notice, possession",
    url: ON_RTA_BASE,
  }],
  ["31", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Order for recovery of possession",
    summary: "Statutory provision dealing with order for recovery of possession.",
    relevance: "possession order, eviction application",
    url: ON_RTA_BASE,
  }],
  ["32", {
    jurisdiction: "Ontario",
    statute: "Residential Tenancies Act, 2006",
    shortName: "RTA",
    title: "Writ of possession",
    summary: "Statutory provision dealing with writ of possession.",
    relevance: "writ of possession, enforcement, sheriff",
    url: ON_RTA_BASE,
  }],

]);

// ── British Columbia: Motor Vehicle Act ──────────────────────────────────────
const BC_MVA_SECTIONS = new Map([
  ["144", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Careless driving prohibited",
    summary: "A person must not drive a motor vehicle on a highway without due care and attention or without reasonable consideration for other persons.",
    relevance: "careless driving, BC traffic law",
    url: `${BC_MVA_BASE}`,
  }],
  ["214.2", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Use of electronic devices while driving",
    summary: "A person must not use an electronic device while driving or operating a motor vehicle on a highway.",
    relevance: "distracted driving, distracted driving BC",
    url: `${BC_MVA_BASE}`,
  }],

  ["98", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Court prohibition against driving",
    summary: "Statutory provision dealing with court prohibition against driving.",
    relevance: "driving prohibition, court order, licence suspension",
    url: BC_MVA_BASE,
  }],
  ["99", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Automatic prohibition against driving on conviction",
    summary: "Statutory provision dealing with automatic prohibition against driving on conviction.",
    relevance: "automatic driving ban, conviction consequences",
    url: BC_MVA_BASE,
  }],
  ["100", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Prohibition against driving for failing to stop",
    summary: "Statutory provision dealing with prohibition against driving for failing to stop.",
    relevance: "fail to stop, driving ban, traffic offence",
    url: BC_MVA_BASE,
  }],
  ["102", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Driving while prohibited by court order or operation of law",
    summary: "Statutory provision dealing with driving while prohibited by court order or operation of law.",
    relevance: "driving while prohibited, court order, traffic offence",
    url: BC_MVA_BASE,
  }],
  ["115.1", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Prohibition against use of electronic device while driving",
    summary: "Statutory provision dealing with prohibition against use of electronic device while driving.",
    relevance: "distracted driving, handheld device use, BC traffic law",
    url: BC_MVA_BASE,
  }],
  ["214.2", {
    jurisdiction: "British Columbia",
    statute: "Motor Vehicle Act",
    shortName: "MVA",
    title: "Use of electronic devices while driving",
    summary: "Statutory provision dealing with use of electronic devices while driving.",
    relevance: "distracted driving, electronic device use, BC traffic law",
    url: BC_MVA_BASE,
  }],

]);

// ── British Columbia: Residential Tenancy Act ────────────────────────────────
const BC_RTA_SECTIONS = new Map([
  ["32", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Landlord and tenant obligations to repair and maintain",
    summary: "A landlord must provide and maintain residential property in a state of decoration and repair that complies with health, safety and housing standards.",
    relevance: "BC tenancy disputes, maintenance",
    url: `${BC_RTA_BASE}`,
  }],

  ["30", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Landlord and tenant obligations to repair and maintain",
    summary: "Statutory provision dealing with landlord and tenant obligations to repair and maintain.",
    relevance: "repairs, maintenance, habitability, BC tenancy",
    url: BC_RTA_BASE,
  }],
  ["31", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Emergency repairs",
    summary: "Statutory provision dealing with emergency repairs.",
    relevance: "emergency repairs, landlord obligations, tenant remedies",
    url: BC_RTA_BASE,
  }],
  ["32", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Landlord must provide and maintain",
    summary: "Statutory provision dealing with landlord must provide and maintain.",
    relevance: "repair and maintenance, health and safety standards",
    url: BC_RTA_BASE,
  }],
  ["33", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Emergency repairs",
    summary: "Statutory provision dealing with emergency repairs.",
    relevance: "urgent repairs, tenant reimbursement, landlord duty",
    url: BC_RTA_BASE,
  }],
  ["47", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Landlord's notice: end of tenancy",
    summary: "Statutory provision dealing with landlord's notice: end of tenancy.",
    relevance: "end of tenancy, notice to end, eviction",
    url: BC_RTA_BASE,
  }],
  ["49", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Landlord's use of property",
    summary: "Statutory provision dealing with landlord's use of property.",
    relevance: "landlord use, termination, personal use",
    url: BC_RTA_BASE,
  }],
  ["50", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Tenant's notice: end of tenancy",
    summary: "Statutory provision dealing with tenant's notice: end of tenancy.",
    relevance: "tenant notice, termination, moving out",
    url: BC_RTA_BASE,
  }],
  ["51", {
    jurisdiction: "British Columbia",
    statute: "Residential Tenancy Act",
    shortName: "RTA",
    title: "Tenant's compensation if notice to end tenancy for landlord's use of property",
    summary: "Statutory provision dealing with tenant's compensation if notice to end tenancy for landlord's use of property.",
    relevance: "tenant compensation, notice to end tenancy, landlord use",
    url: BC_RTA_BASE,
  }],

]);

// ── Alberta: Traffic Safety Act ──────────────────────────────────────────────
const AB_TSA_SECTIONS = new Map([
  ["115", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Careless driving",
    summary: "No person shall drive a vehicle on a highway in a careless manner or without reasonable consideration for others.",
    relevance: "Alberta traffic safety, careless driving",
    url: `${AB_TSA_BASE}`,
  }],
  ["94", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Driving while unauthorized",
    summary: "Prohibits driving while a person's operator's license is suspended or cancelled.",
    relevance: "driving while suspended, Alberta traffic law",
    url: `${AB_TSA_BASE}`,
  }],

  ["94.1", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Driving while disqualified",
    summary: "Statutory provision dealing with driving while disqualified.",
    relevance: "disqualification, licence suspension, Alberta traffic law",
    url: AB_TSA_BASE,
  }],
  ["95", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Driving while prohibited by an immediate roadside sanction",
    summary: "Statutory provision dealing with driving while prohibited by an immediate roadside sanction.",
    relevance: "immediate roadside sanction, driving prohibition",
    url: AB_TSA_BASE,
  }],
  ["115.1", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Cellular telephones, electronic devices, etc.",
    summary: "Statutory provision dealing with cellular telephones, electronic devices, etc..",
    relevance: "distracted driving, handheld device use, Alberta traffic law",
    url: AB_TSA_BASE,
  }],
  ["115.2", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Display screen visible to driver prohibited",
    summary: "Statutory provision dealing with display screen visible to driver prohibited.",
    relevance: "distracted driving, display screen, Alberta traffic law",
    url: AB_TSA_BASE,
  }],
  ["115.3", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Global positioning system",
    summary: "Statutory provision dealing with global positioning system.",
    relevance: "GPS use, distracted driving, Alberta traffic law",
    url: AB_TSA_BASE,
  }],
  ["115.4", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Prohibited activities",
    summary: "Statutory provision dealing with prohibited activities.",
    relevance: "distracted driving, prohibited activities, Alberta traffic law",
    url: AB_TSA_BASE,
  }],
  ["128.1", {
    jurisdiction: "Alberta",
    statute: "Traffic Safety Act",
    shortName: "TSA",
    title: "Safety helmets",
    summary: "Statutory provision dealing with safety helmets.",
    relevance: "helmet requirement, off-highway vehicle safety",
    url: AB_TSA_BASE,
  }],

]);

// ── Alberta: Residential Tenancies Act ───────────────────────────────────────
const AB_RTA_SECTIONS = new Map([
  ["16", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Landlord's covenants",
    summary: "The landlord covenants that the premises will be available for occupation by the tenant at the beginning of the term.",
    relevance: "Alberta tenancy law, landlord obligations",
    url: `${AB_RTA_BASE}`,
  }],

  ["1", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Interpretation",
    summary: "Statutory provision dealing with interpretation.",
    relevance: "Alberta tenancy definitions, landlord tenant terms",
    url: AB_RTA_BASE,
  }],
  ["2", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Application",
    summary: "Statutory provision dealing with application.",
    relevance: "Alberta tenancy coverage, residential premises, exclusions",
    url: AB_RTA_BASE,
  }],
  ["3", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Act prevails",
    summary: "Statutory provision dealing with act prevails.",
    relevance: "statutory priority, tenancy agreement conflicts",
    url: AB_RTA_BASE,
  }],
  ["4", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Crown is bound",
    summary: "Statutory provision dealing with crown is bound.",
    relevance: "provincial tenancy obligations, Crown landlord",
    url: AB_RTA_BASE,
  }],
  ["5", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice of termination of periodic tenancy",
    summary: "Statutory provision dealing with notice of termination of periodic tenancy.",
    relevance: "termination notice, periodic tenancy, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["6", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Termination by landlord",
    summary: "Statutory provision dealing with termination by landlord.",
    relevance: "landlord termination, periodic tenancy, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["7", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice to terminate weekly tenancy",
    summary: "Statutory provision dealing with notice to terminate weekly tenancy.",
    relevance: "weekly tenancy, notice period, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["8", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice to terminate monthly tenancy",
    summary: "Statutory provision dealing with notice to terminate monthly tenancy.",
    relevance: "monthly tenancy, notice period, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["9", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice to terminate yearly tenancy",
    summary: "Statutory provision dealing with notice to terminate yearly tenancy.",
    relevance: "yearly tenancy, notice period, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["10", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Form of notice",
    summary: "Statutory provision dealing with form of notice.",
    relevance: "notice form, termination notice, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["15", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Landlord's covenants",
    summary: "Statutory provision dealing with landlord's covenants.",
    relevance: "landlord obligations, repairs, habitability",
    url: AB_RTA_BASE,
  }],
  ["20", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Tenant's covenants",
    summary: "Statutory provision dealing with tenant's covenants.",
    relevance: "tenant obligations, rent, property care",
    url: AB_RTA_BASE,
  }],
  ["21", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Assignment and sublease",
    summary: "Statutory provision dealing with assignment and sublease.",
    relevance: "assignment, sublease, landlord consent",
    url: AB_RTA_BASE,
  }],
  ["22", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Entry of premises",
    summary: "Statutory provision dealing with entry of premises.",
    relevance: "landlord entry, notice, access",
    url: AB_RTA_BASE,
  }],
  ["23", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Locks and security devices",
    summary: "Statutory provision dealing with locks and security devices.",
    relevance: "tenant security, lock changes, landlord access",
    url: AB_RTA_BASE,
  }],
  ["24", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Landlord's remedies",
    summary: "Statutory provision dealing with landlord's remedies.",
    relevance: "landlord remedies, breach, tenancy enforcement",
    url: AB_RTA_BASE,
  }],
  ["25", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Repudiation of tenancy",
    summary: "Statutory provision dealing with repudiation of tenancy.",
    relevance: "repudiation, abandonment, tenancy end",
    url: AB_RTA_BASE,
  }],
  ["26", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Termination of tenancy for substantial breach",
    summary: "Statutory provision dealing with termination of tenancy for substantial breach.",
    relevance: "breach, termination, landlord notice",
    url: AB_RTA_BASE,
  }],
  ["27", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Termination of tenancy for damage or assault",
    summary: "Statutory provision dealing with termination of tenancy for damage or assault.",
    relevance: "damage, assault, eviction, termination",
    url: AB_RTA_BASE,
  }],
  ["30", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice to vacate",
    summary: "Statutory provision dealing with notice to vacate.",
    relevance: "notice to vacate, eviction notice, possession",
    url: AB_RTA_BASE,
  }],
  ["31", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Order for recovery of possession",
    summary: "Statutory provision dealing with order for recovery of possession.",
    relevance: "possession order, eviction application",
    url: AB_RTA_BASE,
  }],
  ["32", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Writ of possession",
    summary: "Statutory provision dealing with writ of possession.",
    relevance: "writ of possession, enforcement, sheriff",
    url: AB_RTA_BASE,
  }],
  ["33", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Notice to vacate",
    summary: "Statutory provision dealing with notice to vacate.",
    relevance: "notice to vacate, eviction notice, possession",
    url: AB_RTA_BASE,
  }],
  ["34", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Tenant's remedies",
    summary: "Statutory provision dealing with tenant's remedies.",
    relevance: "tenant remedies, repair, landlord breach",
    url: AB_RTA_BASE,
  }],
  ["36", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Compensation to tenant",
    summary: "Statutory provision dealing with compensation to tenant.",
    relevance: "tenant compensation, damages, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["37", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Frustration of tenancy agreement",
    summary: "Statutory provision dealing with frustration of tenancy agreement.",
    relevance: "frustration, tenancy agreement, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["38", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Application for remedy to court",
    summary: "Statutory provision dealing with application for remedy to court.",
    relevance: "court application, tenancy remedy, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["45", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Amount of security deposit",
    summary: "Statutory provision dealing with amount of security deposit.",
    relevance: "security deposit limits, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["46", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Trust account",
    summary: "Statutory provision dealing with trust account.",
    relevance: "security deposit trust account, landlord obligations",
    url: AB_RTA_BASE,
  }],
  ["47", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Interest on deposits",
    summary: "Statutory provision dealing with interest on deposits.",
    relevance: "security deposit interest, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["48", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Return of security deposit",
    summary: "Statutory provision dealing with return of security deposit.",
    relevance: "deposit return, damage claims, Alberta tenancy",
    url: AB_RTA_BASE,
  }],
  ["49", {
    jurisdiction: "Alberta",
    statute: "Residential Tenancies Act",
    shortName: "RTA",
    title: "Obligations and rights of new landlord",
    summary: "Statutory provision dealing with obligations and rights of new landlord.",
    relevance: "new landlord, assignment of tenancy, Alberta tenancy",
    url: AB_RTA_BASE,
  }],

]);

// ── Alberta: Human Rights Act ────────────────────────────────────────────────
const AB_HRA_SECTIONS = new Map([
  ["7", {
    jurisdiction: "Alberta",
    statute: "Alberta Human Rights Act",
    shortName: "AHRA",
    title: "Discrimination in employment",
    summary: "Prohibits discrimination in employment based on protected grounds including race, religious beliefs, colour, gender, etc.",
    relevance: "Alberta human rights, employment discrimination",
    url: `${AB_HRA_BASE}`,
  }],

  ["3", {
    jurisdiction: "Alberta",
    statute: "Alberta Human Rights Act",
    shortName: "AHRA",
    title: "Notices, signs, statements and symbols",
    summary: "Statutory provision dealing with notices, signs, statements and symbols.",
    relevance: "human rights notices, signs, statements, symbols",
    url: AB_HRA_BASE,
  }],
  ["4", {
    jurisdiction: "Alberta",
    statute: "Alberta Human Rights Act",
    shortName: "AHRA",
    title: "Services customarily available to the public",
    summary: "Statutory provision dealing with services customarily available to the public.",
    relevance: "service discrimination, public access, Alberta human rights",
    url: AB_HRA_BASE,
  }],
  ["5", {
    jurisdiction: "Alberta",
    statute: "Alberta Human Rights Act",
    shortName: "AHRA",
    title: "Tenancy",
    summary: "Statutory provision dealing with tenancy.",
    relevance: "housing discrimination, tenancy, Alberta human rights",
    url: AB_HRA_BASE,
  }],
  ["7", {
    jurisdiction: "Alberta",
    statute: "Alberta Human Rights Act",
    shortName: "AHRA",
    title: "Employment",
    summary: "Statutory provision dealing with employment.",
    relevance: "employment discrimination, hiring, firing, Alberta human rights",
    url: AB_HRA_BASE,
  }],

]);

// ── Ontario: Human Rights Code ───────────────────────────────────────────────
const ON_HR_SECTIONS = new Map([
  ["1", {
    jurisdiction: "Ontario",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Right to equal treatment with respect to services, goods and facilities",
    summary: "Statutory provision dealing with right to equal treatment with respect to services, goods and facilities.",
    relevance: "services discrimination, public access, Ontario human rights",
    url: ON_HRC_BASE,
  }],
  ["3", {
    jurisdiction: "Ontario",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Contracts",
    summary: "Statutory provision dealing with contracts.",
    relevance: "contracts discrimination, equal treatment, Ontario human rights",
    url: ON_HRC_BASE,
  }],
  ["4", {
    jurisdiction: "Ontario",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Accommodation of person under eighteen",
    summary: "Statutory provision dealing with accommodation of person under eighteen.",
    relevance: "youth accommodation, age discrimination, Ontario human rights",
    url: ON_HRC_BASE,
  }],
  ["5", {
    jurisdiction: "Ontario",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Employment",
    summary: "Statutory provision dealing with employment.",
    relevance: "employment discrimination, hiring, firing, workplace rights",
    url: ON_HRC_BASE,
  }],
]);

// ── British Columbia: Human Rights Code ──────────────────────────────────────
const BC_HR_SECTIONS = new Map([
  ["8", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in accommodation, service and facility",
    summary: "Statutory provision dealing with discrimination in accommodation, service and facility.",
    relevance: "housing discrimination, services discrimination, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["9", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in purchase of property",
    summary: "Statutory provision dealing with discrimination in purchase of property.",
    relevance: "property purchase discrimination, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["10", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in tenancy premises",
    summary: "Statutory provision dealing with discrimination in tenancy premises.",
    relevance: "tenancy discrimination, housing, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["11", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in employment advertisements",
    summary: "Statutory provision dealing with discrimination in employment advertisements.",
    relevance: "job ads, employment discrimination, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["12", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in wages",
    summary: "Statutory provision dealing with discrimination in wages.",
    relevance: "pay equity, wage discrimination, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["13", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination in employment",
    summary: "Statutory provision dealing with discrimination in employment.",
    relevance: "employment discrimination, hiring, firing, BC human rights",
    url: BC_HRC_BASE,
  }],
  ["14", {
    jurisdiction: "British Columbia",
    statute: "Human Rights Code",
    shortName: "HRC",
    title: "Discrimination by unions and associations",
    summary: "Statutory provision dealing with discrimination by unions and associations.",
    relevance: "union discrimination, association discrimination, BC human rights",
    url: BC_HRC_BASE,
  }],
]);


// ── Master index ──────────────────────────────────────────────────────────────
export const CIVIL_LAW_INDEX = new Map([
  ...Array.from(CDSA_SECTIONS.entries()).map(([k, v]) => [`CDSA s. ${k}`, v]),
  ...Array.from(YCJA_SECTIONS.entries()).map(([k, v]) => [`YCJA s. ${k}`, v]),
  ...Array.from(CHRA_SECTIONS.entries()).map(([k, v]) => [`CHRA s. ${k}`, v]),
  ...Array.from(CC_SENTENCING.entries()).map(([k, v]) => [`CC s. ${k}`, v]),
  ...Array.from(EVIDENCE_SECTIONS.entries()).map(([k, v]) => [`CEA s. ${k}`, v]),
  ...Array.from(CCRA_SECTIONS.entries()).map(([k, v]) => [`CCRA s. ${k}`, v]),
  ...Array.from(ON_HTA_SECTIONS.entries()).map(([k, v]) => [`HTA s. ${k}`, v]),
  ...Array.from(ON_RTA_SECTIONS.entries()).map(([k, v]) => [`ON RTA s. ${k}`, v]),
  ...Array.from(BC_MVA_SECTIONS.entries()).map(([k, v]) => [`MVA s. ${k}`, v]),
  ...Array.from(BC_RTA_SECTIONS.entries()).map(([k, v]) => [`BC RTA s. ${k}`, v]),
  ...Array.from(AB_TSA_SECTIONS.entries()).map(([k, v]) => [`TSA s. ${k}`, v]),
  ...Array.from(AB_RTA_SECTIONS.entries()).map(([k, v]) => [`AB RTA s. ${k}`, v]),
  ...Array.from(AB_HRA_SECTIONS.entries()).map(([k, v]) => [`AHRA s. ${k}`, v]),
  ...Array.from(ON_HR_SECTIONS.entries()).map(([k, v]) => [`HRC (ON) s. ${k}`, v]),
  ...Array.from(BC_HR_SECTIONS.entries()).map(([k, v]) => [`HRC (BC) s. ${k}`, v]),
]);

export { 
  CDSA_SECTIONS, YCJA_SECTIONS, CHRA_SECTIONS, CC_SENTENCING, EVIDENCE_SECTIONS, CCRA_SECTIONS,
  ON_HTA_SECTIONS, ON_RTA_SECTIONS, ON_HR_SECTIONS, BC_MVA_SECTIONS, BC_RTA_SECTIONS, BC_HR_SECTIONS,
  AB_TSA_SECTIONS, AB_RTA_SECTIONS, AB_HRA_SECTIONS
};

const STATUTE_ALIASES = [
  { pattern: /controlled drugs and substances act/i, prefix: "CDSA", map: CDSA_SECTIONS },
  { pattern: /\bCDSA\b/i, prefix: "CDSA", map: CDSA_SECTIONS },
  { pattern: /youth criminal justice act/i, prefix: "YCJA", map: YCJA_SECTIONS },
  { pattern: /\bYCJA\b/i, prefix: "YCJA", map: YCJA_SECTIONS },
  { pattern: /canadian human rights act/i, prefix: "CHRA", map: CHRA_SECTIONS },
  { pattern: /\bCHRA\b/i, prefix: "CHRA", map: CHRA_SECTIONS },
  { pattern: /canada evidence act/i, prefix: "CEA", map: EVIDENCE_SECTIONS },
  { pattern: /\bCEA\b/i, prefix: "CEA", map: EVIDENCE_SECTIONS },
  { pattern: /corrections and conditional release act/i, prefix: "CCRA", map: CCRA_SECTIONS },
  { pattern: /\bCCRA\b/i, prefix: "CCRA", map: CCRA_SECTIONS },
  { pattern: /human rights code\s*\(bc\)|british columbia human rights code|\bHRC\s*\(BC\)/i, prefix: "BC HRC", map: BC_HR_SECTIONS },
  { pattern: /human rights code\s*\(on\)|ontario human rights code|\bHRC\s*\(ON\)/i, prefix: "ON HRC", map: ON_HR_SECTIONS },
  { pattern: /alberta human rights act|human rights act\s*\(ab\)|\bAHRA\b/i, prefix: "AHRA", map: AB_HRA_SECTIONS },
  { pattern: /criminal code/i, prefix: "CC", map: CC_SENTENCING },
  { pattern: /\bCC\b/i, prefix: "CC", map: CC_SENTENCING },
  { pattern: /highway traffic act\s*\(on\)|ontario highway traffic act/i, prefix: "HTA", map: ON_HTA_SECTIONS },
  { pattern: /\bHTA\b/i, prefix: "HTA", map: ON_HTA_SECTIONS },
  { pattern: /residential tenancies act\s*,?\s*2006|residential tenancies act\s*\(on\)|ontario residential tenancies act/i, prefix: "ON RTA", map: ON_RTA_SECTIONS },
  { pattern: /\bON RTA\b/i, prefix: "ON RTA", map: ON_RTA_SECTIONS },
  { pattern: /motor vehicle act\s*\(bc\)|british columbia motor vehicle act/i, prefix: "MVA", map: BC_MVA_SECTIONS },
  { pattern: /\bMVA\b/i, prefix: "MVA", map: BC_MVA_SECTIONS },
  { pattern: /residential tenancy act\s*\(bc\)|british columbia residential tenancy act/i, prefix: "BC RTA", map: BC_RTA_SECTIONS },
  { pattern: /traffic safety act\s*\(ab\)|alberta traffic safety act/i, prefix: "TSA", map: AB_TSA_SECTIONS },
  { pattern: /\bTSA\b/i, prefix: "TSA", map: AB_TSA_SECTIONS },
  { pattern: /residential tenancies act\s*\(ab\)|alberta residential tenancies act/i, prefix: "AB RTA", map: AB_RTA_SECTIONS },
  { pattern: /\bAB RTA\b/i, prefix: "AB RTA", map: AB_RTA_SECTIONS },
];

function extractSectionNumber(citation) {
  const m = citation.match(/s\.\s*([\d.]+(?:\(\w+\))?)/i)
    || citation.match(/section\s+([\d.]+)/i)
    || citation.match(/,\s*([\d.]+(?:\(\w+\))?)\s*$/);
  return m ? m[1].trim() : null;
}

export function lookupCivilLawSection(citation) {
  if (!citation || typeof citation !== "string") return null;
  const trimmed = citation.trim();

  for (const { pattern, prefix, map } of STATUTE_ALIASES) {
    if (pattern.test(trimmed)) {
      const sectionNum = extractSectionNumber(trimmed);
      if (!sectionNum) continue;
      
      let entry = map.get(sectionNum);
      if (!entry) {
        // Fallback: try base section number (e.g., "4(1)" -> "4")
        const baseNum = sectionNum.split("(")[0];
        if (baseNum !== sectionNum) {
          entry = map.get(baseNum);
        }
      }
      
      if (entry) return { entry, prefix };
    }
  }
  return null;
}
