// ESLint flat config. `npm run lint` checks the repo; CI runs it in the
// unit-component-build job.
import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

export default [
  {
    ignores: [
      "dist/**",
      "coverage/**",
      "artifacts/**",
      "playwright-report/**",
      "test-results/**",
      ".claude/**",
      // Generated by scripts/buildCriminalCodeData.mjs (~390KB of data).
      "src/lib/criminalCodeData.js",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,jsx,mjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      // `const { drop: _x, ...rest } = obj` is how we omit a field.
      "no-unused-vars": ["error", { ignoreRestSiblings: true }],
    },
  },
  {
    files: ["src/**/*.{js,jsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    files: ["api/**", "scripts/**", "*.js", "*.mjs"],
    languageOptions: { globals: globals.node },
  },
  {
    // Tests run in Node, but component tests render into happy-dom and E2E
    // specs pass callbacks to page.evaluate() that run in the browser.
    files: ["tests/**"],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    // Dead code that #47 deletes along with the list/string key fix.
    // Remove this block once #47 is merged.
    files: ["api/_retrievalHealthStore.js"],
    rules: { "no-unused-vars": "off", "no-useless-assignment": "off" },
  },
];
